name: opf_late_register
description: OPF Public School Late Register
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=3.3.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.0+2
  shared_preferences: ^2.3.2
  intl: ^0.19.0
  path_provider: ^2.1.4
  csv: ^6.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true
